export const mockData = [
    {
        "id": 29,
        "title": "Fullmetal Alchemist",
        "overview": "Two brothers use alchemy in a desperate quest to restore their bodies.",
        "description": "After a failed alchemic ritual meant to bring their mother back to life, Edward Elric loses his arm and leg, while his brother Alphonse loses his entire body, his soul bound to a suit of armor. Determined to restore themselves, they become State Alchemists and search for the Philosopher’s Stone, encountering other alchemists, soldiers, and homunculi — artificial humans tied to a vast conspiracy. Their journey questions the moral cost of ambition, the meaning of humanity, and the consequences of playing god. Fullmetal Alchemist masterfully blends action, emotion, politics, and philosophy in a deeply impactful story.",
        "author": "Hiromu Arakawa",
        "posterUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746351010/wpv1decjqdioooyf0dys.jpg",
        "backgroundUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746351013/kdzbzm2mx0blr7w9vmri.jpg",
        "createdAt": "2025-05-04T09:30:13.526+00:00",
        "updatedAt": "2025-05-04T09:30:13.526+00:00",
        "chapters": [],
        "genres": [
            "SEINEN",
            "SHOJO",
            "SHONEN",
            "ISEKAI",
            "SLICE_OF_LIFE",
            "SUPERNATURAL",
            "COMEDY",
            "MARTIAL_ARTS",
            "PSYCHOLOGICAL",
            "HISTORICAL",
            "ADVENTURE",
            "REVERSE_HAREM",
            "DEMONS",
            "SCI_FI"
        ]
    },
    {
        "id": 28,
        "title": "Dandadan",
        "overview": "Two teens get caught in a bizarre battle between aliens and ghosts.",
        "description": "High school students Momo Ayase, who believes in ghosts, and Okarun, who believes in aliens, decide to prove each other wrong. However, their investigations awaken supernatural and extraterrestrial threats that target them. Momo unlocks spiritual powers, while Okarun gains super speed from a cursed possession. They must fight off absurd and dangerous entities while protecting each other and their loved ones. With a blend of horror, sci-fi, romance, and comedy, Dandadan stands out for its unpredictable storytelling, high-energy artwork, and its weirdly charming duo at the center of the chaos.",
        "author": "Yukinobu Tatsu",
        "posterUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350954/upfpm5pzzxww4qbpizny.jpg",
        "backgroundUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350957/zm6nn0octhul6m3fvtbi.jpg",
        "createdAt": "2025-05-04T09:29:17.593+00:00",
        "updatedAt": "2025-05-04T09:29:17.593+00:00",
        "chapters": [
            {
                "id": 3,
                "chapterIndex": 1,
                "pages": [
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351058/n52xuvjwuwrctarq0fyq.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351061/nyjzz6xc1926hag9vmvr.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351064/oxfkrq1sajb3v8kmhzda.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351066/vjvw6vaiiunkwucldnhm.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351069/kuvbprjlmakmhtc6pmgo.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351072/rzhyfyz4am1bbojjgrnh.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351075/kwpn037rjkkos6rpwaqv.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351083/owqa5tczru2nlawvcosx.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351086/yhaojfba24cqa814qfia.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351089/g6sogoh6ymtj37gf6hko.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351091/buepvrbe7xeg74zqmbcs.png"
                ],
                "title": "Chapter 1",
                "readTimes": 0,
                "createdAt": "2025-05-04T09:31:32.430+00:00",
                "updatedAt": "2025-05-04T09:31:32.430+00:00"
            }
        ],
        "genres": [
            "SHOJO",
            "MECHA",
            "SEINEN",
            "ADVENTURE",
            "VAMPIRE",
            "HAREM",
            "GAME",
            "PSYCHOLOGICAL",
            "ROMANCE",
            "SPORTS",
            "SUPERNATURAL",
            "SCI_FI"
        ]
    },
    {
        "id": 27,
        "title": "Vinland Saga",
        "overview": "A Viking warrior seeks revenge and meaning in a brutal world.",
        "description": "A Viking warrior seeks revenge and meaning in a brutal world.\",\r\n    \"description\": \"Thorfinn, the son of a legendary warrior, witnesses his father's death and joins the mercenary band led by the man responsible. Fueled by revenge, he grows into a formidable fighter, only to find that vengeance brings emptiness. As the story progresses, Thorfinn is forced to confront his past and reevaluate his purpose in a world plagued by violence. Based on historical events and Norse mythology, Vinland Saga is a gripping and philosophical journey that explores war, pacifism, redemption, and the search for a land free of conflict — a true 'Vinland'.",
        "author": "Makoto Yukimura",
        "posterUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350883/gsnr5apg43gnupwcxsk4.jpg",
        "backgroundUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350886/uctrrha9bjh40nry0yip.jpg",
        "createdAt": "2025-05-04T09:28:06.593+00:00",
        "updatedAt": "2025-05-04T09:28:06.593+00:00",
        "chapters": [],
        "genres": [
            "SHONEN",
            "SEINEN",
            "ISEKAI",
            "MECHA",
            "PSYCHOLOGICAL",
            "HAREM",
            "GAME",
            "DEMONS",
            "HISTORICAL",
            "SUPERNATURAL",
            "COMEDY",
            "FANTASY",
            "SCI_FI"
        ]
    },
    {
        "id": 26,
        "title": "Naruto",
        "overview": "A mischievous ninja dreams of becoming the Hokage.",
        "description": "Naruto Uzumaki, a prankster and outcast in the Hidden Leaf Village, carries the powerful Nine-Tailed Fox spirit sealed inside him, making him feared by others. Despite his lonely childhood, Naruto is determined to earn respect and become the Hokage, the strongest ninja and leader of the village. As he trains, joins Team 7, and forms bonds with Sasuke and Sakura, he faces dangerous missions, internal village politics, and external threats like the Akatsuki organization. The story evolves into a large-scale tale of war, legacy, and identity, emphasizing perseverance, forgiveness, and the power of connection.",
        "author": "Masashi Kishimoto",
        "posterUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350814/u7ozmlioqfzdgzgjba6j.jpg",
        "backgroundUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350816/x4tgydsn5gbhfifxtjhn.jpg",
        "createdAt": "2025-05-04T09:26:57.194+00:00",
        "updatedAt": "2025-05-04T09:26:57.194+00:00",
        "chapters": [],
        "genres": [
            "SEINEN",
            "MECHA",
            "JOSEI",
            "MUSIC",
            "DEMONS",
            "GAME",
            "REVERSE_HAREM",
            "HAREM",
            "SPORTS",
            "COMEDY",
            "SCI_FI"
        ]
    },
    {
        "id": 25,
        "title": "Golden Kamuy",
        "overview": "A veteran soldier and an Ainu girl hunt for hidden gold in Hokkaido.",
        "description": "Saichi Sugimoto, known as 'Immortal Sugimoto' for surviving countless battles in the Russo-Japanese War, discovers a rumor about a hidden stash of Ainu gold. To find it, he must track down escaped convicts whose bodies are tattooed with the map's pieces. He is joined by Asirpa, a young Ainu girl with wilderness skills and personal stakes in the treasure. Their perilous journey across snowy Hokkaido involves clashes with military factions, criminal outlaws, and other treasure hunters. The series combines historical insight, action, and survival with a focus on Ainu culture, food, and identity.",
        "author": "Satoru Noda",
        "posterUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350755/uc3cfqyxtjwapj3vyhaj.jpg",
        "backgroundUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350757/vuyogt9ngocoucxczaue.avif",
        "createdAt": "2025-05-04T09:25:58.179+00:00",
        "updatedAt": "2025-05-04T09:25:58.179+00:00",
        "chapters": [],
        "genres": [
            "SHOJO",
            "SHONEN",
            "MECHA",
            "JOSEI",
            "MUSIC",
            "GAME",
            "VAMPIRE",
            "ADVENTURE",
            "ROMANCE",
            "SUPERNATURAL",
            "SPORTS",
            "FANTASY",
            "SCI_FI"
        ]
    },
    {
        "id": 24,
        "title": "Dungeon Meshi",
        "overview": "A party of adventurers survives dungeon crawling by eating monsters.",
        "description": "After losing their supplies and a teammate in a dungeon mishap, Laios and his party decide to press on rather than retreat. To survive, they begin preparing meals using the very monsters they encounter, including giant bats, slimes, and basilisks. As they continue their quest to rescue Laios' sister, who was devoured by a dragon, they encounter odd allies and deadly foes. Blending culinary creativity with fantasy adventure, the manga uniquely mixes humor, strategy, and heartwarming moments as the party questions what it truly means to live and fight in such a dangerous, ever-changing world.",
        "author": "Ryoko Kui",
        "posterUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350690/dn3v1quukbjb9wt5ggfw.jpg",
        "backgroundUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350692/hmsimjydafbwbe6yqni2.jpg",
        "createdAt": "2025-05-04T09:24:53.029+00:00",
        "updatedAt": "2025-05-04T09:24:53.029+00:00",
        "chapters": [
            {
                "id": 4,
                "chapterIndex": 1,
                "pages": [
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351263/qcn3aprgpsp8asc3bygs.jpg",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351266/jsjxbidsmj41we57bnm4.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351269/yliobzpheafptmziaay5.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351271/arkbfvm0fsq9ajynjogp.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351281/i53binhqojz6orczztnd.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351284/znm32latdzlgxreiwdzp.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351287/geqv3ffs5aruuwmglqxg.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351290/aolmbn4zbnf64jplwzwl.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351293/c1q5okanl8hfunxj9nnu.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351296/jyhzawclwaniaqgaltea.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351299/a8zmy1b9awrxyxmcv37m.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351301/bjwqqeho3xzdtmsmdu5t.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351304/nxmtraliiqrgivcquvt9.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351327/arw2yeo8qmptcbljbtv6.png"
                ],
                "title": "Chapter 1",
                "readTimes": 0,
                "createdAt": "2025-05-04T09:35:28.482+00:00",
                "updatedAt": "2025-05-04T09:35:28.482+00:00"
            },
            {
                "id": 5,
                "chapterIndex": 2,
                "pages": [
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351389/hm0qy6f4zynrr2xcgd8p.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351392/jgxlvxb9onexb6wzgeqr.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351394/luw7bqejjjaxsrwayzo1.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351403/nmidxscjr8fop8xk2mgj.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351406/tpgxqriruqhvyiglpjvu.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351408/qwwiniwk5xghb9lmu0uv.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351419/bkfbaohvmt0b4mzgi5wb.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351422/oc9hfsibf6v6cidcpzcx.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351425/vkxm2rodas0dsol1wqmx.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351429/rnre8r9ivnwpmmz0oacy.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351432/i2r87lrcg5kw8fdl0vzb.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351435/qqaemocqrpljve1qrazq.png"
                ],
                "title": "Chapter 2",
                "readTimes": 0,
                "createdAt": "2025-05-04T09:37:15.838+00:00",
                "updatedAt": "2025-05-04T09:37:15.838+00:00"
            },
            {
                "id": 6,
                "chapterIndex": 3,
                "pages": [
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351466/m86x8t8o2rsvmeshtahg.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351475/o9warj6cpuyzaqexvz2l.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351478/tzlyvrynpdjxyenjz8te.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351486/mtqhkawn88e9iefpuvxv.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351489/ctpu42nbp2gluojpvlwf.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351491/rusnvbni8c7gstzop7cd.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351494/uka8peginrtbkowmnzyn.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351497/slyoxighdlq2ypwdmazc.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351500/emqd1cva9izbociiv7g9.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351503/nrc2e1i7csyltughlwxh.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351508/piqjd5syzb7krtj9gx9q.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351511/hcvjheoxczxnpvrlnwey.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351517/nthjfqo2lluwbx56tyim.png"
                ],
                "title": "Chapter 3",
                "readTimes": 0,
                "createdAt": "2025-05-04T09:38:38.496+00:00",
                "updatedAt": "2025-05-04T09:38:38.496+00:00"
            },
            {
                "id": 7,
                "chapterIndex": 4,
                "pages": [
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351553/quurccexllugr7svbsix.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351556/njtpaz0p0atkjkicrrzb.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351558/pynjjip3cdc7uyetm00k.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351561/x0wdrj9333y74qvp9knc.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351564/ebizbi6nxnldtb6eioh5.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351567/kl9gzdduijbgxpjmoolw.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351569/bm8yis72bhxfjz2khcyz.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351572/e3rbxez17pbdoq3dzwwv.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351575/bgjruwbblnzzlmfmpwzr.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351578/hawjseq2lggk0ldaolv0.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351580/sodredgsaayvdxbahriv.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351583/rtesy21w5kdly95xmsvm.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351586/ywpgvhswtuy2r4vjjhrj.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351593/yjrvaaqqn48sz1hv9pcb.png"
                ],
                "title": "Chapter 4",
                "readTimes": 0,
                "createdAt": "2025-05-04T09:39:54.086+00:00",
                "updatedAt": "2025-05-04T09:39:54.086+00:00"
            },
            {
                "id": 8,
                "chapterIndex": 5,
                "pages": [
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351644/emfqclqogatzaykkiot1.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351647/nyq2zsolcoti7druya3t.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351649/zhi159hhzjqqmzkf2tt8.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351652/snpbdrotp9zvcxmuwzbg.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351655/ecp8v64oj86kd3cxsblb.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351657/jbolbnnwwkquml2xmwn8.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351660/yq051lboe8s2xvj565yz.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351662/omjmbjiiad47bkq5choa.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351665/v0locmwm2kowczf6jyvt.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351668/oed20zcazyeyvmvalsw4.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351670/xhn4fcwnoajowe4iplfg.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351679/fpa3yikly5qduebavugg.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351682/cusvkly9lb7tqeuae4py.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351684/fclq8w5opfqpmwkyjtuy.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351687/rwpl5s6mrlvjpndlknxk.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351689/eekvdivwrwyikzbadaek.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351694/pbxzulclyd5zp0jckj8v.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351697/oao53vlgpe7uigvqzhgm.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351700/aj8p9qalntfrtfxdsmm4.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351708/os3pr53lrdv0al5onqot.png",
                    "http://res.cloudinary.com/djst6i5om/image/upload/v1746351711/xjwmb6ejkc3xkrcgptxn.png"
                ],
                "title": "Chapter 5",
                "readTimes": 0,
                "createdAt": "2025-05-04T09:41:52.253+00:00",
                "updatedAt": "2025-05-04T09:41:52.253+00:00"
            }
        ],
        "genres": [
            "SHOJO",
            "JOSEI",
            "ISEKAI",
            "SHONEN",
            "ROMANCE",
            "MYSTERY",
            "SCI_FI",
            "HISTORICAL",
            "GAME"
        ]
    },
    {
        "id": 23,
        "title": "Sousou no Frieren",
        "overview": "An elf mage explores life and humanity after a hero's journey ends.",
        "description": "Decades after completing an epic journey to defeat the Demon King, the elven mage Frieren finds herself grappling with the passage of time and the mortality of her human comrades. As an immortal being, she barely noticed the years she spent with her party, but the loss of her friends stirs a desire to understand them better. Determined to learn more about human emotions and experiences, she embarks on a new journey with new companions. The story deeply explores themes of grief, memory, and what it means to truly connect with others in a world where time flows differently for everyone.",
        "author": "Kanehito Yamada & Tsukasa Abe",
        "posterUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350623/xbosdt0zmccuz7axmrev.jpg",
        "backgroundUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350630/twdchzoqpm0amdqoodnz.jpg",
        "createdAt": "2025-05-04T09:23:50.558+00:00",
        "updatedAt": "2025-05-04T09:23:50.558+00:00",
        "chapters": [],
        "genres": [
            "SLICE_OF_LIFE",
            "FANTASY",
            "SHOJO",
            "SHONEN",
            "JOSEI",
            "MARTIAL_ARTS",
            "HAREM",
            "GAME",
            "PSYCHOLOGICAL",
            "VAMPIRE"
        ]
    },
    {
        "id": 22,
        "title": "Pokemon",
        "overview": "A young trainer begins an adventure to become a Pokémon Master.",
        "description": "Set in a world where humans and Pokémon coexist, the story follows Ash Ketchum, a passionate and determined young boy from Pallet Town who dreams of becoming a Pokémon Master. With his first partner, Pikachu, he travels from region to region, capturing new Pokémon, challenging Gym Leaders, and competing in tournaments. Along the way, Ash makes lifelong friends and faces recurring threats from Team Rocket, a comical yet persistent group seeking to steal powerful Pokémon. The series explores themes of friendship, perseverance, and the bond between humans and their Pokémon companions.",
        "author": "Hidenori Kusaka",
        "posterUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350505/g3xafdf2ugkbutoflhz3.jpg",
        "backgroundUrl": "http://res.cloudinary.com/djst6i5om/image/upload/v1746350508/cv3ao5y7zidb3jqzjzvl.jpg",
        "createdAt": "2025-05-04T09:21:48.590+00:00",
        "updatedAt": "2025-05-04T09:21:48.590+00:00",
        "chapters": [],
        "genres": [
            "SHOJO",
            "MECHA",
            "JOSEI",
            "SEINEN",
            "SUPERNATURAL",
            "COMEDY",
            "MARTIAL_ARTS",
            "SPORTS",
            "PSYCHOLOGICAL"
        ]
    }
]